version: '3'

services:

  website:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file: .env.dev
   
  postgres:
    image: postgres:15.4
    env_file: .env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: