default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: postgres

production:
  <<: *default
  database: dgrpool

development:
  <<: *default
  database: dgrpool


test:
  <<: *default
  database: dgrpool

